### ISSUE TITLE
TO DO!

### ISSUE THREAD

**Issue by Opartl** [fialov33/JKOD#10]
SeeNowDo:

- userstories

-  předělat na role a funkčnost v rámci sprintu má být realizována celá userstory udělat na sprint zpětnou vazbu
- story musí po jeho skončení fungovat

- předělat hodnocení příběhů - máme tam málo hodin
změnit metriku

- zohlednit hodinové ocenění

- udělat to více barevné

- úkol by měl mít 10-12hodin

- udělat storypointy

- usersotry musí být ve správném formátu

Github:

- více konverzace

**Comment by doskoc04** [comment]
Pracuji na opravě chyb na SeeNowDo.

**Comment by Opartl** [comment]
Paráda, zejtra to ještě doupravíme.
