### ISSUE TITLE
Group meeting 

### ISSUE THREAD

**Issue by Opartl** [fialov33/JKOD#11]

**Comment by Opartl** [comment]
V průběhu týdne meeting a rozprava o problémech či nápadech apod.

**Comment by Opartl** [comment]
Napište návrhy na datum , kdy se sejdeme. Jsem pro pátek (10.11) po PWA. Co vy ?

**Comment by fialov33** [comment]
Nešlo by to před PWA? Já pak jedu po pwa do Prahy

**Comment by zelenk11** [comment]
pokud to je v pátek tak je mi to jedno

**Comment by doskoc04** [comment]
Já v pátek před PWA můžu.

**Comment by Opartl** [comment]
Dohodnuto 10.11.2017  od 10:00 v pc učebně.
