### ISSUE TITLE
RETROSPEKTIVA

### ISSUE THREAD

**Issue by Opartl** [fialov33/JKOD#13]
Jak již jsem už psal - v DOKUMENTECH --> RETROSPEKTIVA  je potřeba v poslední kapitole (STAR FISH ANALÝZA) doplnit do každého pole svůj názor - MINIMÁLNĚ 1 KE KAŽDÉMU. 

Takže postup zní: 
1) Popořadě si stáhnete dokument - domluvte se kdo bude první, druhej, třetí ! 
2) Doplníte ty potřebné věci
3)Nahrajete zpět  A DÁ VĚDĚT OSTATNÍM, ŽE TAK PROVEDL

A dokument pak stáhne druhý, udělá to samé v postupu nahoře a pokračuje 3.  .......

TAKŽE SE DOMLUVTE KDO BUDE PRVNÍ, DRUHÝ A TŘETÍ a proveďte to!

**Comment by doskoc04** [comment]
Přidal jsem do dokumentu **Retrospektiva** své poznámky, uploadoval jsem novou verzi.

**Comment by fialov33** [comment]
Přidala jsem do dokumentu Retrospektiva své poznámky
