### ISSUE TITLE
Restrospektiva SPRINTU 2

### ISSUE THREAD

**Issue by Opartl** [fialov33/JKOD#15]
Pro lepší pružnost už nemusíte oblasti co zlepšit, co bylo dobrý / špatný psát přímo do dokumentu. Stačí když tady každý z vás dá koment ve stylu:

1) V ČEM POKRAČOVAT :    "v systematické práci"
2) CO DĚLAT VÍCE: " více mezi sebou komunikovat o problémech"
3) CO NEDĚLAT: "neřešit věci nad rámec zadání"
4) S ČÍM ZAČÍT: "používat nástroje"
5) CO DĚLAT MÉNĚ: "neplnit své úkoly"

**Comment by doskoc04** [comment]
V ČEM POKRAČOVAT : "pravidelné meetingy"
CO DĚLAT VÍCE: "aktivněji komentovat issues na gitu"
CO NEDĚLAT: "nepracovat na stejném problému samostatně, ale jako tým - případně určená část týmu"
S ČÍM ZAČÍT: "efektivně plánovat a držet se plánu"
CO DĚLAT MÉNĚ: "méně vybočovat z naplánovaných postupů"

**Comment by fialov33** [comment]
V ČEM POKRAČOVAT : "dodržování plánu"
CO DĚLAT VÍCE: "komunikovat na github"
CO NEDĚLAT: "nechávat si pro sebe připomínky a nápady"
S ČÍM ZAČÍT: "otevřeně mluvit o svých nápadech"
CO DĚLAT MÉNĚ: "oddalovat plnění úkolů"
