### ISSUE TITLE
Uživatelské role

### ISSUE THREAD

**Issue by Opartl** [fialov33/JKOD#2]

**Comment by Opartl** [comment]
Kluci promyslete si nějaký základy. Jaký uživatelský role by tak mohli být.....

**Comment by zelenk11** [comment]
do branch dokumenty přidán txt s několika uživatelskými příběhy co mě napadly

**Comment by fialov33** [comment]
Super

**Comment by doskoc04** [comment]
Upraven soubor uživatelské příběhy - přidán návrh hodnocení.
